name: check

on:
  pull_request: 
    branches: 
      - main
      - release

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node_modules
      run: yarn install
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
