name: Build & Deploy
on:
  push:
    branches: [development/docker]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      GOOGLE_RESOURCE_ID: ${{ secrets.GOOGLE_RESOURCE_ID }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PGHOST: ${{ secrets.PGHOST }}
      PGUSER: ${{ secrets.PGUSER }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      PGPORT: ${{ secrets.PGPORT }}
      REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
      REACT_APP_ADDR_NAME: ${{ secrets.REACT_APP_ADDR_NAME }}
      REACT_APP_JWT_SECRET: ${{ secrets.REACT_APP_JWT_SECRET }}
      REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            git clone git@github.com:ValeryDrozd/Astrology-Social-Network.git
            git checkout development/docker
            cd Astrology-Social-Network
            docker-compose build
            docker-compose up -d
            echo 'Deployment successful to digital ocean' 